import { Inter } from 'next/font/google';

import type { Metadata } from 'next';

import './globals.css';

import type { ReactNode } from 'react';
import type { LayoutType } from '@/app/types/common-types';

import { GlobalProviders } from './components/global-providers';
import { ThemeToggle } from './components/theme-toggle';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: LayoutType) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProviders>
          <header className="flex h-16 items-center justify-end p-4">
            <ThemeToggle />
          </header>
          {children}
        </GlobalProviders>
      </body>
    </html>
  );
}
